#!/usr/bin/perl

print "Generating new .args-file for Denmark ...\n";

open(FIL, "template.args") or die "*** Can not open file \"template.args\"\n";
open(NYFIL, ">nyfil.args") or die "*** Can not create file \"nyfil.args\"\n";
while($line=<FIL>) {
   
   if($line =~ "mapname:") {
      print $line;
      print NYFIL "description: OSM map. Made by nickoe and other contribuators.\n";
      print NYFIL "country-name: Denmark\n";
      print NYFIL "country-abbr: DK\n";
   
   }
   if($line =~ "input-file:") {
   print NYFIL $line;
   print NYFIL "\n";

   } 
   
}

close FIL;
close NYFIL;

print "Finished making new .args-file for Denmark ...\n";
