#!/usr/bin/perl

print "Lager ny .args-fil for Danmark ...\n";

open(FIL, "template.args") or die"*** Kan ikke åpne fil \"template.args\".\n";
open(NYFIL, ">nyfil.args") or die "Kan ikke opprette fil \"nyfil.args\".\n";
while($line=<FIL>) {
   
   if($line =~ "mapname:") {
      print $line;
      print NYFIL "description: OSM map. Made by ArchLinux\n";
      print NYFIL "country-name: Denmark\n";
      print NYFIL "country-abbr: DA\n";
   
   }
   if($line =~ "input-file:") {
   print NYFIL $line;
   print NYFIL "\n";

   } 
   
}

close FIL;
close NYFIL;

# print "Ferdig. \n";
